services:
  # 数据库服务
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysql?577715
      MYSQL_DATABASE: imagedb
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysql577715
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongo577715
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "redis577715"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis577715", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: miniouser
      MINIO_ROOT_PASSWORD: minio577715
    ports:
      - "9110:9110"
      - "9111:9111"
    volumes:
      - minio_data:/data
    command: server /data --console-address :9111 --address :9110
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9110/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  milvus:
    image: milvusdb/milvus:v2.2.9
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9110
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - etcd
      - minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      timeout: 20s
      retries: 3

  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - etcd_data:/etcd
    command: etcd --advertise-client-urls=http://127.0.0.1:2379 --listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  # 后端API服务
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      DB_URL: "mysql+asyncmy://mysqluser:mysql577715@mysql/imagedb"
      MONGODB_URL: "mongodb:27017"
      MONGODB_DB: "mongodb"
      MONGODB_ROOT_USERNAME: "mongouser"
      MONGODB_ROOT_PASSWORD: "mongo577715"
      REDIS_URL: "redis:6379"
      REDIS_PASSWORD: "redis577715"
      SECRET_KEY: "TestCodeForLLMProject"
      ALGORITHM: "HS256"
      MINIO_URL: "http://minio:9110"
      MINIO_ACCESS_KEY: "miniouser"
      MINIO_SECRET_KEY: "minio577715"
      MINIO_BUCKET_NAME: "ai-chat"
      MILVUS_URI: "http://milvus:19530"
      # OpenRouter配置 - API密钥从.env文件读取
      USE_API_EMBEDDING: "true"
      EMBEDDING_API_URL: "https://openrouter.ai/api/v1"
      EMBEDDING_MODEL_NAME: "openai/text-embedding-3-large"
      IMAGE_EMBEDDING_MODEL_NAME: "openai/gpt-4o"
      # 以下为可选配置，不设置则不发送站点信息
      # SITE_URL: "https://your-website.com"
      # SITE_NAME: "Your App Name"
    depends_on:
      mysql:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
      milvus:
        condition: service_healthy

  # 模型服务器
  model_server:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "model_server.py"]
    env_file:
      - ./.env
    depends_on:
      - backend

  # 前端服务
  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: "http://backend:8000"
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql_data:
  mongodb_data:
  redis_data:
  minio_data:
  etcd_data: 