name: LAYRA CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    steps:
      - uses: actions/checkout@v3
      
      - name: 设置Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: 登录Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: 构建并推送后端镜像
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/layra-backend:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/layra-backend:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/layra-backend:buildcache,mode=max
      
      - name: 设置Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json
      
      - name: 构建前端
        run: |
          cd web
          npm install
          npm run build
      
      - name: 构建并推送前端镜像
        uses: docker/build-push-action@v4
        with:
          context: ./web
          file: ./web/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/layra-frontend:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/layra-frontend:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/layra-frontend:buildcache,mode=max
          
  deploy-to-server:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        
      - name: 配置SSH密钥
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          if_key_exists: replace
      
      - name: 将文件传输到服务器
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
          
          # 只传输docker-compose.yml文件，使用服务器上的.env
          scp docker-compose.yml ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/opt/layra/
          
          # 创建部署脚本并传输
          cat > deploy.sh << EOL
          #!/bin/bash
          cd /opt/layra
          
          # 检查.env文件是否存在，并提供建议
          if [ -f .env ]; then
            echo "发现.env文件，检查API模式设置..."
            if grep -q "USE_API_EMBEDDING=" .env; then
              echo "USE_API_EMBEDDING配置已存在"
              current_setting=\$(grep "USE_API_EMBEDDING=" .env | cut -d= -f2)
              if [ "\$current_setting" != "true" ]; then
                echo "警告: 当前USE_API_EMBEDDING=\$current_setting，建议设置为true以使用API模式"
                echo "如需修改，请编辑.env文件"
              else
                echo "当前配置为API模式，推荐设置"
              fi
            else
              echo "警告: 未找到USE_API_EMBEDDING配置，建议添加USE_API_EMBEDDING=true到.env文件"
              echo "如需添加，请编辑.env文件"
            fi
          else
            echo "警告: 未找到.env文件，请创建.env文件并添加必要的配置"
            echo "推荐设置USE_API_EMBEDDING=true以使用API模式"
          fi
          
          # 拉取最新镜像
          docker-compose pull
          
          # 停止所有容器
          docker-compose down -v
          
          # 启动所有服务
          docker-compose up -d
          EOL
          chmod +x deploy.sh
          scp deploy.sh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/opt/layra/
      
      - name: 执行远程部署
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /opt/layra && chmod +x deploy.sh && ./deploy.sh" 